<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>bd7261d8-78f9-4b7b-877f-c3d018da20c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.is-success.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='manual-order-pharmapack']/div/div/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6240cd0d-59ce-4149-b27a-504af321cf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-success mr-1</value>
      <webElementGuid>971ad513-776d-40b8-b7f5-dae44a88311e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>32512c73-af0c-43d2-b89b-a1189c30c1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manual-order-pharmapack&quot;)/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns mt-minus-30&quot;]/div[@class=&quot;column dis-flex justify-end&quot;]/button[@class=&quot;button is-success mr-1&quot;]</value>
      <webElementGuid>c9550342-c843-48b1-95af-7815750cf41e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manual-order-pharmapack']/div/div/div[3]/div[2]/button</value>
      <webElementGuid>452ec5d8-aeb5-4ee3-bc49-7ca2a42fbdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send link pembayaran ke customer'])[1]/following::button[1]</value>
      <webElementGuid>73cfc17c-39f5-4378-add7-34c1209c0abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminder untuk penebusan berikutnya'])[1]/following::button[1]</value>
      <webElementGuid>550dcd6a-2942-41f0-8688-8008bbb98d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>30d87735-f2b1-463a-9e4b-e8c0e9c4f542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>b67621fb-ba32-4486-866e-87108ea1711f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>74f1ed64-6525-4580-8dfe-c5ba7c1ea05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
