<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>afe932b1-a9ca-4fb5-a189-2325765b2d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.modal-card-body.medication-dialog-edit-children > div:nth-of-type(2) > footer.modal-card-foot > button.button.is-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-medication-dialog']/div/div[2]/section/div[2]/footer/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46eb81bc-c30c-4cc4-94e1-5118361338f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-success</value>
      <webElementGuid>6b320632-ece2-43e2-8431-f87421379138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>323b4f85-ddf3-40d1-84aa-d45b4dc4d6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-medication-dialog&quot;)/div[@class=&quot;modal is-active&quot;]/div[@class=&quot;modal-card medication-dialog-add-parent&quot;]/section[@class=&quot;modal-card-body medication-dialog-edit-children&quot;]/div[2]/footer[@class=&quot;modal-card-foot&quot;]/button[@class=&quot;button is-success&quot;]</value>
      <webElementGuid>29f147ae-197b-4a80-abfe-b853036266cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-medication-dialog']/div/div[2]/section/div[2]/footer/button</value>
      <webElementGuid>40921418-cbf1-44f8-a841-7eb116835a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan untuk Pasien'])[1]/following::button[1]</value>
      <webElementGuid>20f15faa-5658-4195-890f-8e06da5d6c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama Konsumsi*'])[1]/following::button[1]</value>
      <webElementGuid>6046ce18-0f9b-458c-9557-7ea10c046f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::button[1]</value>
      <webElementGuid>4845e20e-5420-4397-af40-2671baf85e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama*'])[1]/preceding::button[3]</value>
      <webElementGuid>4ae8a72e-1afe-420f-b2de-abd5d6cbd748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>db999d49-4a7c-4e53-bf9e-30dfa2a7b624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/footer/button</value>
      <webElementGuid>c71664af-7a62-493c-901b-0f04f2f42fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>0ea9dd11-410e-4049-92b4-7a86a93faae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
