<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Total_input</name>
   <tag></tag>
   <elementGuidId>7f9515ee-9832-4852-af4d-98b418113496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dis-flex.flex-row > input.input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-medication-dialog']/div/div[2]/section/div[2]/div/div[14]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13305ddb-a006-42b7-9f54-39eebd5a7155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cec8490-5d63-4f01-a85f-443dff129e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-medication-dialog&quot;)/div[@class=&quot;modal is-active&quot;]/div[@class=&quot;modal-card medication-dialog-add-parent&quot;]/section[@class=&quot;modal-card-body medication-dialog-edit-children&quot;]/div[2]/div[@class=&quot;dis-flex flex-col&quot;]/div[@class=&quot;field dis-flex&quot;]/div[@class=&quot;field-body dis-flex flex-col&quot;]/div[@class=&quot;dis-flex flex-row&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>8f648471-22c6-4b0c-8737-67301495af50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-medication-dialog']/div/div[2]/section/div[2]/div/div[14]/div[2]/div/input</value>
      <webElementGuid>d669655c-db24-49d6-b01e-7df603e0e21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/input</value>
      <webElementGuid>f24b51c1-301a-4a85-8f77-35a1294f6444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
