<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upload</name>
   <tag></tag>
   <elementGuidId>82171cad-9810-404e-b133-bc901e2cbc6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.file-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='manual-order-pharmapack']/div/div/div/div/div/nav/div/div[2]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62dadcfd-ead5-4127-841b-67055c44e345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-cta</value>
      <webElementGuid>b6a99aa7-975d-4f82-9e6a-3687f213c1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>9bfc8d75-8fbe-402f-bdfb-eb2158319352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manual-order-pharmapack&quot;)/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns is-variable&quot;]/div[@class=&quot;column is-5 pos-relative&quot;]/div[@class=&quot;colums prescription-image-sticky&quot;]/nav[@class=&quot;panel&quot;]/div[@class=&quot;panel-block&quot;]/div[@class=&quot;action-image mt-2 dis-flex align-center&quot;]/div[@class=&quot;file&quot;]/label[@class=&quot;file-label&quot;]/span[@class=&quot;file-cta&quot;]</value>
      <webElementGuid>e22c1fd0-fe42-483c-8a6c-63bab20f0679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manual-order-pharmapack']/div/div/div/div/div/nav/div/div[2]/div/label/span</value>
      <webElementGuid>8ffbe03e-5ce7-4d2c-bc57-fadbc82fb6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Resep'])[1]/following::span[1]</value>
      <webElementGuid>22c69793-c4ef-4fcd-95da-1024f46bb0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/following::span[1]</value>
      <webElementGuid>f342eed0-4cde-4b6f-8163-4662c4fba57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[2]/preceding::span[3]</value>
      <webElementGuid>67ff5405-ec97-4e4d-a887-2eaf5b17b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>452496b0-ab40-4345-82b5-208169bc0f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>5c0dadfb-5dfe-426e-a872-8b39077a8b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
